version: '2'
services:
  influxdb:
    image: influxdb
    hostname: influxdb
    domainname: service.com
  redis:
    image: redis
    hostname: redis
    domainname: service.com
  agador:
    image: amancevice/agador
    hostname: agador
    domainname: service.com
    command: --config /home/agador/example.yaml
    volumes:
      - ./example.yaml:/home/agador/example.yaml
  notebook:
    build: .
    command: sh -c "jupyter notebook --ip=* --no-browser"
    ports:
      - "8888:8888"
    volumes:
      - ./example.ipynb:/example/example.ipynb
    links:
      - agador:agador.service.com
      - influxdb:influxdb.service.com
      - redis:redis.service.com
