language: python
python:
  - "2.7"
install:
  - pip install tox
script:
  - tox
deploy:
  provider: pypi
  user: amancevice
  password:
    secure: SUeP7n1QC4hEnXgRqTzjpFOilMDKJUBixi0n0YcBL7+Pl/Mp+E6VoxaawoVR5No24FG+pLdr6Cv/8Lr3sQbCjwBR0P3XWvY2QJ64kqjmcTqxLFrdfiiUZlFbJzkiffvW7RpItQOO3mTrIDlZGHqTfg7N/WvkHPC1pMcrzPObsq6vPUq2w2xvQKZzCKEOmxC7Wi973oPZYGXD1SDN9FHzOIkdDZUk9gDJOKmbnuFfulWxZUKGqtjyswgSUV945u8SNNx30tjTMGlbitFY4yt/Jcfu0Auh44OiEBJaTfkQLXH/LDqnTGccdoUhfiCunxoIgVgJKbE+yHzFfmOZxxMNpF6Nl0O9GDRC2OeQk/4I5JPBd+NWYyRAC1htDnZkeyHxc/vT3P9l/wvV72P3E7KP1kufr75ND3X5iu6RB3EcKlMvw29APSe9pCMpKBAMrEK5XAT7AObtUmg/9lFFfERJX1R3TpXGCDYPVL9z/XyQZpVPji7ULjdybrrRk8E0MFOFs2c5ij+7OyPqRpJRo4mbzWxkkgUQ+2odg6TawJQd7kLTbaQXhP7rKx3J2ZoFr9Z//J+b3SNX1N9fvEnSHfwoP2qYtWDGvmWzdFUzlsw+hPAo7OcUIYNNtLQCTpM9hlvKceMQqz98T4QIX/XSOkSdRq1wh2oMOdU+1I/AXmk/jRk=
  on:
    tags: true
    repo: amancevice/agador
